name: build test

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: build in native linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install libva-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y libva-dev meson ninja-build

      - name: build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          SKIPINSTALL=yes VERBOSE=yes SKIPRAV1E=yes ./build-ffmpeg --build --enable-gpl-and-non-free
          kill %1
      - name: check shared library
        run: |
          ldd ./workspace/bin/ffmpeg
      - name: test run ffmepg
        run: |
          ./workspace/bin/ffmpeg -buildconf
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux
          path: workspace/bin/
      - name: clean up
        run: |
          ./build-ffmpeg --cleanup

  build-macos:
    name: build in native macOS
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug m4
        run: |
          echo "=== Debugging m4 ==="
          which -a m4 || true
          m4 --version 2>&1 || true
          echo "exit code of m4 --version: $?"
          echo "===================="
      - name: build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          SKIPINSTALL=yes VERBOSE=yes ./build-ffmpeg --build
          kill %1
      - name: check shared library
        run: |
          otool -L ./workspace/bin/ffmpeg
      - name: test run ffmepg
        run: |
          ./workspace/bin/ffmpeg -buildconf
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-macos
          path: workspace/bin/
      - name: clean up
        run: |
          ./build-ffmpeg --cleanup

  build-docker:
    name: build in docker
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: pull base image
        id: ubuntu_pull
        run: |
          docker pull ubuntu:24.04
      - name: run if ubuntu_pull failed
        if: failure() && steps.ubuntu_pull.outcome == 'failure'
        run: |
          docker pull ubuntu:24.04
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:ubuntu -f Dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:ubuntu -buildconf
      - name: save docker image
        run: |
          docker save ffmpeg:ubuntu | gzip > ffmpeg-ubuntu.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-docker-ubuntu
          path: ffmpeg-ubuntu.tar.gz

  build-cuda-ubuntu-docker:
    name: build in ubuntu docker with cuda
    runs-on: ubuntu-22.04
    steps:
      - name: Free up disk space
        run: |
          rm -rf /usr/share/dotnet && rm -rf /opt/ghc && rm -rf "/usr/local/share/boost"
          rm -rf /opt/hostedtoolcache && cd /opt && find . -maxdepth 1 -mindepth 1 '!' -path ./containerd '!' -path ./actionarchivecache '!' -path ./runner '!' -path ./runner-cache -exec rm -rf '{}' ';'
          docker system prune -af
      - name: Checkout code
        uses: actions/checkout@v4
      - name: pull base image
        id: cuda_ubuntu_pull
        run: |
          docker pull nvidia/cuda:12.6.2-devel-ubuntu22.04
          docker pull ubuntu:22.04
      - name: run if cuda_ubuntu_pull failed
        if: failure() && steps.cuda_ubuntu_pull.outcome == 'failure'
        run: |
          docker pull nvidia/cuda:12.6.2-devel-ubuntu22.04
          docker pull ubuntu:22.04
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:cuda-ubuntu -f cuda-ubuntu.dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:cuda-ubuntu -buildconf
      - name: save docker image
        run: |
          docker save ffmpeg:cuda-ubuntu | gzip > ffmpeg-cuda-ubuntu.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-docker-cuda-ubuntu
          path: ffmpeg-cuda-ubuntu.tar.gz

  build-full-static:
    name: full static build in docker
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: pull base image
        id: cuda_ubuntu_pull
        run: |
          docker pull nvidia/cuda:12.6.2-devel-ubuntu22.04
      - name: run if cuda_ubuntu_pull failed
        if: failure() && steps.cuda_ubuntu_pull.outcome == 'failure'
        run: |
          docker pull nvidia/cuda:12.6.2-devel-ubuntu22.04
      - name: build ffmpeg
        run: |
          docker build -t ffmpeg:cuda-static -f full-static.dockerfile .
      - name: test run ffmepg
        run: |
          docker run --rm ffmpeg:cuda-static -buildconf
      - name: save docker image
        run: |
          docker save ffmpeg:cuda-static | gzip > ffmpeg-cuda-static.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-docker-cuda-static
          path: ffmpeg-cuda-static.tar.gz

  build-windows:
    name: build in Windows (MSYS2)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-make
            mingw-w64-x86_64-dlfcn
            autoconf
            automake
            libtool
            make
            git
            curl
            unzip
            python
            gettext-devel


      - name: Checkout code
        uses: actions/checkout@v4

      - name: build ffmpeg
        env:
          MSYS: winsymlinks:copy
        run: |
          SKIPINSTALL=yes VERBOSE=yes SKIPRAV1E=yes ./build-ffmpeg --build --enable-gpl-and-non-free

      - name: test run ffmpeg
        run: |
          ./workspace/bin/ffmpeg.exe -buildconf

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows
          path: workspace/bin/*.exe
